from snakemake.utils import min_version

min_version("6.10.0")


# Configuration file containing all user-specified settings
configfile: "config/config.yml"


import os
import csv
import pandas as pd


BIOPROJ=pd.read_csv('data/metadata.csv').bioproject.unique().tolist()

with open('data/bioproj_accessions.txt', 'w') as f:
    print(BIOPROJ, file=f)


report: "report/workflow.rst"

include: "rules/process_tidy_metadata.smk"
include: "rules/merge_bioproj_metadata.smk"
include: "rules/read_size_table.smk"
# include: "rules/plot_var_read_freq.smk"
include: "rules/plot_sampling_map.smk"
include: "rules/create_mapping_files.smk"
include: "rules/rmd_report.smk"



rule all:
    input:
        "config/pe_samples.tsv",
        "config/pe_units.tsv",
        "resources/metadata/pe_metadata.tsv",
        # "figures/read_size.svg",
        "images/sample_gps_py.html",
        "index.html",

