channels:
  - conda-forge
  - bioconda
  - r
  - anaconda
dependencies:
  - snakemake =7.19.1
  - snakemake-minimal =7.19.1
  - python =3.11.0
  - r-base =4.3
  - r-tidyverse >=1.3.2 
  - r-bookdown >=0.32
  - r-htmltools >=0.5.4 
  - r-htmlwidgets >=1.6.1
  - r-rmarkdown >=2.20
  

