name: srametadata
channels:
  - conda-forge
  - bioconda
  - defaults
  - r
dependencies:
  - snakemake =7.19.1
  - snakemake-minimal =7.19.1
  - python =3.11.0
  # - r-base =4.1.3
  # - r-tidyverse =1.3.2 
  # - r-bookdown =0.32
  # - r-htmltools =0.5.4 
  # - r-htmlwidgets =1.6.1
  # - r-leaflet >=2.2.1
  # - r-leaflet.providers =1.9.0 
  # - r-rmarkdown =2.20
  - graphviz =6.0.1
  - entrez-direct =16.2
